---
title: "kobe_explore"
output: html_document
---

```{r packages, message = FALSE}

library(ggplot2)
library(dplyr)

```

```{r load and split data}

df <- read.csv('~/kaggle/kobe/data.csv')

df$shot_made_flag <- factor(df$shot_made_flag, level = c('1', '0'))

train <- df[!is.na(df$shot_made_flag), ]
test <- df[is.na(df$shot_made_flag), ]

```

```{r accuracy by plots}

ggacc <- function(feature) {
  ggplot(
    train, 
    aes_string(
      paste0('x = ', feature)
      )
    ) +
    geom_bar(
      aes(fill = shot_made_flag), 
      stat = 'count', 
      position = 'fill',
      color = 'black'
    )
}

```

```{r acc plots, echo = FALSE}

ggacc('combined_shot_type')
ggacc('shot_zone_range')

```

```{r shot chart by type, echo = FALSE}

ggplot(
  train %>% 
    dplyr::filter(shot_distance < 35), 
  aes(x = lon, y = lat)
  ) + 
  geom_point(
    aes(color = combined_shot_type), 
    alpha = .5, 
    size = 2
    ) + 
  scale_color_brewer(palette = 'Set1')

```

```{r makes shot chart}
ggplot()+
  geom_point(
    data = train %>% 
      dplyr::filter(shot_distance < 35, shot_made_flag == 1), 
    aes(x = lon, y = lat),
    color = 'gold',
    size = 2
  ) + 
  geom_point(
    data = train %>% 
      dplyr::filter(shot_distance < 35, shot_made_flag == 0), 
    aes(x = lon, y = lat),
    color = 'purple',
    alpha = .5
  ) +
  theme(
    panel.background = element_rect(fill = 'darkgrey'),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

```