---
title: "Instacart Modeling"
author: "James Kim"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup}
devtools::load_all('.')
library(data.table)
library(dplyr)
library(magrittr)
library(MASS)
library(scales)
library(ggplot2)
```

```{r utils}
# based on https://github.com/benhamner/Metrics/blob/master/R/R/metrics.r
f1 <- function (actual, predicted) {
  act <- as.character(strsplit(actual, ' ')[[1]])
  pred <- as.character(strsplit(predicted, ' ')[[1]])
  
  tp <- length(intersect(act,pred))
  fp <- length(setdiff(pred,act))
  fn <- length(setdiff(act,pred))
  
  precision <- ifelse ((tp==0 & fp==0), 0, tp/(tp+fp))
  recall <- ifelse ((tp==0 & fn==0), 0, tp/(tp+fn))
  
  score <- ifelse ((precision==0 & recall==0), 0, 2*precision*recall/(precision+recall))
  return(score)
}

evalerror <- function(preds, dtrain) {
  labels <- as.numeric(getinfo(dtrain, 'label'))
  preds <- as.numeric(preds > .5)
  tp <- sum(preds[labels == 1] == 1)
  fp <- sum(preds[labels == 0] == 1)
  fn <- sum(preds[labels == 1] == 0)
  
  precision <- ifelse((tp == 0 & fp == 0), 0, tp / (tp + fp))
  recall <- ifelse((tp == 0 & fn == 0), 0, tp / (tp + fn))
  
  score <- ifelse((precision == 0 & recall == 0), 0, 2 * precision * recall / (precision + recall))
  return(list(metric = 'f1', value = score))
}
```

```{r data}
data(aisles)
data(departments)
data(order_products_prior)
data(order_products_train)
data(orders)
data(products)
data(sample_submission)

setkey(orders, order_id)
setkey(order_products_prior, order_id)
prior_orders <- orders[eval_set == 'prior'][order_products_prior]

setkey(products, product_id)
setkey(prior_orders, product_id)
prior_orders <- products[prior_orders]

dataset <- order_products_train %>% 
  dplyr::left_join(y = orders %>% 
                     dplyr::select(order_id, user_id) %>% 
                     unique(), 
                   by = 'order_id') %>% 
  dplyr::group_by(user_id, order_id) %>%
  tidyr::nest() %>%
  dplyr::mutate(
    actual_products = purrr::map_chr(
      data, 
      ~paste(.x$product_id[.x$reordered == 1], collapse = ' ')
    ),
    product_ids = purrr::map2(
      user_id,
      data,
      ~prior_orders[user_id == .x, 'product_id'] %>% 
        unique() %>%
        dplyr::left_join(y = .y %>% 
                           dplyr::select(-add_to_cart_order), 
                         by = 'product_id') %>%
        dplyr::mutate(reordered = replace(reordered, is.na(reordered), 0))
    ),
    set = 'train'
  ) %>%
  rbind(
    sample_submission %>%
      dplyr::select(order_id) %>%
      dplyr::left_join(y = orders %>%
                         dplyr::select(order_id, user_id) %>%
                         unique(),
                       by = 'order_id') %>%
      dplyr::mutate(
        data = purrr::map(user_id, ~NULL),
        actual_products = purrr::map_chr(user_id, ~NA),
        product_ids = purrr::map(
          user_id,
          ~prior_orders[user_id == .x, 'product_id'] %>% 
            unique() %>%
            dplyr::mutate(reordered = NA)
        ),
        set = 'test'
      )
  ) %>%
  dplyr::mutate(actual_products = replace(actual_products,
                                          actual_products == '',
                                          'None'))

sample_submission %<>%
  dplyr::left_join(y = dataset %>% 
                     dplyr::filter(set == 'test') %>%
                     dplyr::select(user_id, order_id),
                   by = 'order_id')

dependent_info <- orders %>% 
  dplyr::group_by(user_id) %>% 
  tidyr::nest() %>% 
  dplyr::mutate(
    order_id = purrr::map_int(
      data, 
      ~.x$order_id[.x$order_number == max(.x$order_number)]
    ), 
    days_since_prior_order = purrr::map_dbl(
      data, 
      ~.x$days_since_prior_order[.x$order_number == max(.x$order_number)]
    ),
    order_dow = purrr::map_dbl(
      data,
      ~.x$order_dow[.x$order_number == max(.x$order_number)]
    ),
    order_hour_of_day = purrr::map_dbl(
      data,
      ~.x$order_hour_of_day[.x$order_number == max(.x$order_number)]
    ),
    eval_set = purrr::map_chr(
      data, 
      ~.x$eval_set[.x$order_number == max(.x$order_number)]
    )
  ) %>% 
  dplyr::select(-data)
```

```{r baseline}
# for each user in test set, choose products he / she reordered over 50% of the time
baseline <- cust_df %>%
  dplyr::select(user_id, data) %>%
  tidyr::unnest() %>%
  dplyr::filter(!is.na(reordered)) %>%
  dplyr::group_by(user_id, product_id) %>%
  dplyr::summarise(perc_reordered = sum(reordered) / n()) %>%
  dplyr::group_by(user_id) %>%
  dplyr::summarise(products = paste(product_id[perc_reordered > .5], 
                                    collapse = ' ')) %>%
  dplyr::right_join(y = dataset %>%
                      dplyr::filter(set == 'test') %>%
                      dplyr::select(user_id, order_id),
                    by = 'user_id') %>%
  dplyr::select(order_id, products) %>%
  dplyr::arrange(order_id)

# f score of .3110698
```

```{r customer-info}
cust_df <- prior_orders %>% 
  dplyr::group_by(user_id) %>% 
  tidyr::nest() %>% 
  dplyr::mutate(
    user_order_freq = purrr::map_dbl(data, 
                                     ~mean(.x$days_since_prior_order, na.rm = TRUE)),
    user_dow = purrr::map_dbl(data,
                              ~mean(.x$order_dow, na.rm = TRUE)),
    user_hour = purrr::map_dbl(data,
                               ~mean(.x$order_hour_of_day, na.rm = TRUE)),
    cart_size = purrr::map_dbl(data, 
                               ~.x %>% dplyr::count(order_id) %>% .$n %>% mean()), 
    user_perc_reorder = purrr::map_dbl(data, 
                                  ~sum(.x$reordered) / nrow(.x)),
    perc_department = purrr::map(data,
                                 ~.x %>% 
                                   dplyr::count(department_id) %>% 
                                   dplyr::mutate(perc_order = n / sum(n)) %>% 
                                   dplyr::left_join(y = departments, 
                                                    by = 'department_id'))
  )

cust_profile <- cust_df %>% 
  dplyr::select(user_id, user_order_freq, user_dow,
                user_hour, cart_size, 
                user_perc_reorder, perc_department) %>% 
  tidyr::unnest(perc_department) %>%
  dplyr::select(-department_id, -n) %>% 
  tidyr::spread(department, perc_order, fill = 0) %>%
  dplyr::left_join(y = dataset %>%
                     dplyr::select(user_id, set),
                   by = 'user_id')

# use customer group as feature or just use entire custoemr profile?
lda_train <- cust_profile[cust_profile$set == 'train', ]
lda_test <- cust_profile[cust_profile$set == 'test', ]
set <- 2:4
cluster <- kmeans(lda_train[set], 5)

lda_train$customer_group = as.factor(cluster$cluster)

lda <- MASS::lda(customer_group ~ ., data = lda_train[c(set, ncol(lda_train))])
# plda <- predict(lda, newdata = lda_test[set])
# prop.lda <- lda$svd^2 / sum(lda$svd^2)
# 
# ggplot(data.frame(customer_group = plda$class,
#                   lda = plda$x)) +
#   geom_point(aes(x = lda.LD1, y = lda.LD2,
#                  color = customer_group), alpha = .5) +
#   labs(x = paste0('LD1 (', scales::percent(prop.lda[1]), ')'),
#        y = paste0('LD2 (', scales::percent(prop.lda[2]), ')'))

plda <- predict(lda, newdata = cust_profile[set])

cust_profile$customer_group <- plda$class
```
  
```{r product-info}
tmp <- cust_df %>%
  dplyr::select(user_id, data) %>%
  tidyr::unnest(data)

# particular user's behavior for a particual product
user_prod <- tmp %>%
  dplyr::group_by(user_id, product_id) %>%
  dplyr::summarise(
    user_prod_orders = n(),
    user_prod_avg_days_reordered = mean(days_since_prior_order[reordered == 1]),
    user_prod_reordered_perc = sum(reordered) / n(),
    user_prod_dow_reordered = mean(order_dow[reordered == 0]),
    user_prod_hour_reordered = mean(order_hour_of_day[reordered == 1])
  )

# product features, population use training set only
prod_df <- tmp %>%
  dplyr::left_join(y = dataset %>%
                     dplyr::select(user_id, set),
                   by = 'user_id') %>%
  dplyr::filter(set == 'train') %>%
  dplyr::group_by(product_id) %>%
  dplyr::summarise(
    prod_orders = n(),
    prod_avg_days_reordered = mean(days_since_prior_order[reordered == 1]),
    prod_dow_reordered = mean(order_dow[reordered == 1]),
    prod_hour_reordered = mean(order_hour_of_day[reordered == 1]),
    prod_reordered_perc = sum(reordered) / n()
  )

department_df <- tmp %>%
  dplyr::left_join(y = dataset %>%
                     dplyr::select(user_id, set),
                   by = 'user_id') %>%
  dplyr::filter(set == 'train') %>%
  dplyr::group_by(department_id) %>%
  dplyr::summarise(
    department_orders = n(),
    department_avg_days_reordered = mean(days_since_prior_order[reordered == 1]),
    department_reordered_perc = sum(reordered) / n()
  )

aisle_df <- tmp %>%
  dplyr::left_join(y = dataset %>%
                     dplyr::select(user_id, set),
                   by = 'user_id') %>%
  dplyr::filter(set == 'train') %>%
  dplyr::group_by(aisle_id) %>%
  dplyr::summarise(
    aisle_orders = n(),
    aisle_avg_days_reordered = mean(days_since_prior_order[reordered == 1]),
    aisle_reordered_perc = sum(reordered) / n()
  )
```

```{r model-df}
model_df <- dataset %>%
  dplyr::select(user_id, set, product_ids) %>%
  tidyr::unnest() %>%
  dplyr::left_join(y = cust_profile %>%
                     dplyr::select(user_id, user_order_freq, cart_size, 
                                   user_perc_reorder, user_dow, user_hour),
                   by = 'user_id') %>%
  dplyr::left_join(y = user_prod,
                   by = c('user_id', 'product_id')) %>%
  dplyr::left_join(y = products %>% dplyr::select(-product_name),
                   by = 'product_id') %>%
  dplyr::left_join(y = dependent_info %>% dplyr::select(-eval_set),
                   by = 'user_id') %>%
  dplyr::left_join(y = department_df, by = 'department_id') %>%
  dplyr::left_join(y = aisle_df, by = 'aisle_id') %>%
  dplyr::left_join(y = prod_df, by = 'product_id') %>%
  # mutate_at with dplyr::ends_with('id') not working?
  dplyr::mutate(reordered = as.factor(reordered),
                product_id = as.factor(product_id),
                aisle_id = as.factor(aisle_id),
                department_id = as.factor(department_id),
                user_diff_days = days_since_prior_order - user_order_freq,
                user_diff_dow = order_dow - user_dow,
                user_diff_hour = order_hour_of_day - user_hour,
                prod_diff_days = days_since_prior_order - prod_avg_days_reordered,
                prod_diff_dow = order_dow - prod_dow_reordered, 
                prod_diff_hour = order_hour_of_day - prod_hour_reordered,
                department_diff = days_since_prior_order - department_avg_days_reordered,
                aisle_diff = days_since_prior_order - aisle_avg_days_reordered)
```

```{r logistic}
# .2482304
library(Matrix)
library(glmnet)
library(doParallel)

# x <- Matrix::sparse.model.matrix(
#   reordered ~ ., 
#   model_df %>% 
#     dplyr::filter(set == 'train', 
#                   !is.na(prod_avg_days_reordered)) %>% 
#     dplyr::select(-user_id, -set, -product_id, -aisle_id, -department_id)
# )

x <- data.matrix(
  model_df %>% 
    dplyr::filter(set == 'train', 
                  !is.na(prod_avg_days_reordered),
                  !is.na(reordered)) %>% 
    dplyr::select(-user_id, -set, -product_id, -aisle_id, 
                  -department_id, -reordered, -order_id)
)

x <- Matrix::cBind(
  x, 
  Matrix::sparse.model.matrix(
    ~model_df$customer_group[model_df$set == 'train' & !is.na(model_df$prod_avg_days_reordered) & !is.na(model_df$reordered)] - 1
  )
)

colnames(x)[(ncol(x)-4):ncol(x)] <- paste0('cust_group', 1:5)

y <- model_df$reordered[model_df$set == 'train' & !is.na(model_df$prod_avg_days_reordered) & !is.na(model_df$reordered)]

registerDoParallel(2)
logit <- glmnet(
  x = x,
  y = y,
  family = 'binomial',
  alpha = .5
)

rm(x, y)
gc()

newx <- data.matrix(
  model_df %>% 
    dplyr::filter(set == 'test', 
                  !is.na(prod_avg_days_reordered)) %>% 
    dplyr::select(-user_id, -set, -product_id, -aisle_id, 
                  -department_id, -reordered, -order_id)
)

newx <- Matrix::cBind(
  newx, 
  Matrix::sparse.model.matrix(
    ~model_df$customer_group[model_df$set == 'test' & !is.na(model_df$prod_avg_days_reordered)] - 1
  )
)

colnames(newx)[(ncol(newx)-4):ncol(newx)] <- paste0('cust_group', 1:5)
preds <- predict(logit, s = .01, newx = newx, type = 'response')

logit_preds <- model_df %>%
  dplyr::filter(set == 'test', 
                  !is.na(prod_avg_days_reordered)) %>%
  dplyr::select(order_id, product_id) %>%
  dplyr::mutate(preds = as.numeric(preds), 
                take = preds >= .1) %>%
  dplyr::group_by(order_id) %>%
  dplyr::summarise(products = paste(product_id[take], collapse = ' ')) %>%
  dplyr::right_join(y = sample_submission %>% dplyr::select(-products),
                    by = 'order_id') %>%
  dplyr::mutate(products = replace(products, products == '', 'None'))
```


```{r xgboost}
# 0.3338959
library(xgboost)

pos <- model_df %>%
  dplyr::filter(set == 'train',
                reordered == 1)

neg <- model_df %>%
  dplyr::filter(set == 'train',
                reordered == 0) %>%
  dplyr::sample_n(nrow(pos) * 2)

train <- rbind(pos, neg)

x <-  data.matrix(train %>%
                    dplyr::select(-user_id, -set, -product_id, -aisle_id, 
                                  -department_id, -reordered, -order_id))

y <- as.numeric(as.character(train$reordered))

X <- xgb.DMatrix(x, label = y)

params <- list('objective' = 'binary:logistic', 'eta' = .1, 
               'max_depth' = 6, 'min_child_weight' = 10, 'gamma' = .7,
               'subsample' = .76, 'colsample_bytreee' = .95, 
               'alpha' = 2e-5, 'lambda' = 10, 'maximize' = TRUE)

# bst <- xgb.cv(data = X, params = params, 
#               feval = evalerror, nrounds = 20, nfold = 5)

bst <- xgboost(data = X, params = params, 
               feval = evalerror, nrounds = 20)

preds <- predict(bst, X)

bst_preds <- train %>%
  dplyr::mutate(preds = preds) %>%
  dplyr::group_by(order_id) %>%
  dplyr::summarise(products = paste(product_id[preds > .5], collapse = ' ')) %>%
  dplyr::mutate(products = replace(products, products == '', 'None')) %>%
  dplyr::left_join(dataset %>% dplyr::select(order_id, actual_products),
                   by = 'order_id')

mean_f1 <- mean(apply(bst_preds, 1, function(x) f1(x[3], x[2])))

newx <- data.matrix(
  model_df %>% 
    dplyr::filter(set == 'test') %>% 
    dplyr::select(-user_id, -set, -product_id, -aisle_id, 
                  -department_id, -reordered, -order_id)
)

newx <- xgb.DMatrix(newx)

preds <- predict(bst, newx)
bst_preds <- model_df %>%
  dplyr::filter(set == 'test') %>%
  dplyr::select(order_id, product_id) %>%
  dplyr::mutate(preds = preds > .5) %>%
  dplyr::group_by(order_id) %>%
  dplyr::summarise(products = paste(product_id[preds], collapse = ' ')) %>%
  dplyr::right_join(y = sample_submission %>% dplyr::select(-products),
                    by = 'order_id') %>%
  dplyr::mutate(products = replace(products, products == '', 'None'))
```
